/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Facu
 */
public class nuevoProd extends javax.swing.JFrame {

    /**
     * Creates new form nuevoProd
     */
    public nuevoProd() {
        initComponents();
        setLocation(230,90);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lineaProd = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        LabelPrecio = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LabelLinea = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        precioProd = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        LabelNombreProd = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        nombreProd = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        nombreProd2 = new javax.swing.JTextPane();
        LabelTipo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tipoProd = new javax.swing.JTextPane();
        botonGuardarNP = new javax.swing.JButton();
        botonCancelarNP = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 0));
        setForeground(new java.awt.Color(153, 153, 0));
        setMaximumSize(new java.awt.Dimension(800, 420));
        setMinimumSize(new java.awt.Dimension(800, 420));
        setPreferredSize(new java.awt.Dimension(800, 420));
        setResizable(false);
        getContentPane().setLayout(null);

        jScrollPane1.setViewportView(lineaProd);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(190, 280, 198, 29);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel1.setText("ID Producto");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 80, 120, 23);

        LabelPrecio.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        LabelPrecio.setText("Precio");
        getContentPane().add(LabelPrecio);
        LabelPrecio.setBounds(20, 280, 60, 26);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(877, 231, 0, 0);

        LabelLinea.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        LabelLinea.setText("Linea");
        getContentPane().add(LabelLinea);
        LabelLinea.setBounds(20, 210, 50, 26);

        jScrollPane3.setViewportView(precioProd);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(190, 210, 198, 29);

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 30)); // NOI18N
        jLabel5.setText("AGREGAR NUEVO PRODUCTO");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(180, 20, 460, 30);

        LabelNombreProd.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        LabelNombreProd.setText("Nombre Producto");
        getContentPane().add(LabelNombreProd);
        LabelNombreProd.setBounds(20, 140, 150, 23);

        nombreProd.setToolTipText("");
        nombreProd.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane4.setViewportView(nombreProd);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(190, 140, 198, 28);

        nombreProd2.setToolTipText("");
        nombreProd2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane5.setViewportView(nombreProd2);

        getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(190, 80, 197, 22);

        LabelTipo.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        LabelTipo.setText("Tipo");
        getContentPane().add(LabelTipo);
        LabelTipo.setBounds(20, 350, 50, 30);

        jScrollPane2.setViewportView(tipoProd);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(190, 350, 198, 30);

        botonGuardarNP.setText("Guardar");
        botonGuardarNP.setEnabled(false);
        botonGuardarNP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarNPActionPerformed(evt);
            }
        });
        getContentPane().add(botonGuardarNP);
        botonGuardarNP.setBounds(510, 180, 133, 30);

        botonCancelarNP.setText("Cancelar");
        botonCancelarNP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarNPActionPerformed(evt);
            }
        });
        getContentPane().add(botonCancelarNP);
        botonCancelarNP.setBounds(510, 230, 133, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 800, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGuardarNPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarNPActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonGuardarNPActionPerformed

    private void botonCancelarNPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarNPActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonCancelarNPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nuevoProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nuevoProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nuevoProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nuevoProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new nuevoProd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelLinea;
    private javax.swing.JLabel LabelNombreProd;
    private javax.swing.JLabel LabelPrecio;
    private javax.swing.JLabel LabelTipo;
    private javax.swing.JButton botonCancelarNP;
    private javax.swing.JButton botonGuardarNP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextPane lineaProd;
    private javax.swing.JTextPane nombreProd;
    private javax.swing.JTextPane nombreProd2;
    private javax.swing.JTextPane precioProd;
    private javax.swing.JTextPane tipoProd;
    // End of variables declaration//GEN-END:variables
}
